#!/bin/bash

# Luuakse muutuja ja  antakse talle väärtus 2016
aasta=2016
# Luuakse muutuja ja ja  antakse talle  väärtus "Kersti Kaljulaid"
president="Kersti Kaljulaid"
# Luuakse muutuja ja  antakse talle  väärtus ". aastal valiti Eesti presidendiks "
lause_keskosa=". aastal valiti Eesti presidendiks "
# Luuakse muutuja lause, ühendtatakkse muutujad
lause="$aasta$lause_keskosa$president"
# näitakse värki
echo "$lause"
