#!/bin/bash

# Küsi userilt  ainepunkte
read -p "anna mulle ainepunktide arv: " ainepunktid

#Küsi kasutajalt nädalate arv
read -p "anna mulle nädalate arv: " nadalad

# Arvutame kogu
aeg=$(echo "$ainepunktid * 26" | bc)

#Arvutame
ajakulu=$(echo "scale=2; $aeg / $nadalad" | bc)

# Ümardame
umbes_ajakulu=$(echo "($ajakulu + 0.9)/1" | bc)

# näitame tulemuse ekraanile
echo "Ühe nädala ajakulu on ilmselt $umbes_ajakulu tundi."
